export {
  absurd,
  apply,
  cast as unsafeCoerce,
  cast,
  compose,
  constant,
  // flip,
  constFalse,
  constNull,
  constTrue,
  constUndefined,
  constVoid,
  dual,
  type FunctionN,
  type FunctionTypeLambda,
  flow,
  identity,
  type LazyArg,
  pipe,
  satisfies,
  tupled,
  untupled,
} from "effect/Function";
export { isFunction } from "effect/Predicate";
