const arr: {
  from: string;
  name: "*" | (string & {});
  as?: string;
}[] = JSON.parse(await Bun.file("./tmp/auto-import.json").text());

type Dest =
  | {
      _tag: "ns";
      ns: string;
      import: string;
    }
  | {
      _tag: "const";
      const: string;
    };
const codex = arr.map((importD): Dest => {
  if (importD.name === "*") {
    return {
      _tag: "ns",
      import: `import * as ${importD.as || importD.name} from "${importD.from}"`,
      ns: `declare namespace ${importD.as || importD.name} { export * from "${importD.from}"; }`,
    };
  }
  return {
    _tag: "const",
    const: `const ${importD.as || importD.name}: typeof import("${importD.from}").${importD.name};`,
  };
});

let head = [
    `/* eslint-disable */
/** biome-ignore-all assist/source/organizeImports: auto-generated */
/** biome-ignore-all lint/correctness/noUnusedImports: auto-generated */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {};
`,
  ],
  globalBody = [];
for (const code of codex) {
  if (code._tag === "ns") {
    head.push(code.import);
    globalBody.push(code.ns);
  } else {
    globalBody.push(code.const);
  }
}
Bun.file("./src/auto-imports.d.ts").write(
  head.join("\n") +
    `
declare global {
${globalBody.map((_) => "  " + _).join("\n")}
}`,
);

export {};
